#!/bin/bash
# capture_screens.sh — capture a UI screenshot on the iOS simulator for PR review.
#
# Canonical copy lives in forkable/scripts/ (base template); child repos pull
# synced copies. Do not edit this file child-first — pull from forkable.
# Excluded from the pre-commit gate (needs a running simulator; the gate runs
# analyze + test only).
#
# Usage:
#   capture_screens.sh <screen-name> [--out <dir>] [--no-backend] [--device <name|udid>] [--reuse-installed]
#
# Screen registry: docs/features/<feature>/screens.yaml — fields per entry:
#   name, route, deep_link, initial, needs_auth, needs_backend.
# Adding a UI-visible screen = adding a registry entry; no script change needed.
# The registry is per-app data and lives in each app repo (not mirrored).
#
# Exit codes:
#   0 ok · 1 invalid args / unknown screen · 2 simulator unavailable ·
#   3 backend unreachable (needs_backend screen without --no-backend) ·
#   4 app launch/crash · 5 navigation/settle timeout · 6 screenshot write failure
set -euo pipefail

# --- Repo + delivery ---------------------------------------------------------
# Repo-agnostic: derive the repo root from this script's own location.
if [ -n "${REPO_OVERRIDE:-}" ]; then
  REPO="$REPO_OVERRIDE"
else
  REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
# shellcheck disable=SC1091
. "$REPO/scripts/report_sink.sh"

# --- Defaults ----------------------------------------------------------------
DEFAULT_DEVICE_UDID="4509FAFA-4512-4A69-9B2C-4D72307916E8" # iPhone 16 Pro Max (accepted bar, 08-06)
BACKEND_BASE="${BACKEND_BASE_URL:-http://127.0.0.1:8000}"
SETTLE_POLL_SECS=15
FIXED_WAIT_SECS=5
MIN_PNG_BYTES=5120

SCREEN=""
OUT_DIR=""
DEVICE=""
NO_BACKEND=0
REUSE_INSTALLED=0

usage() {
  cat >&2 <<'EOF'
Usage: capture_screens.sh <screen-name> [--out <dir>] [--no-backend] [--device <name|udid>] [--reuse-installed]

  <screen-name>       name from docs/features/*/screens.yaml
  --out <dir>         output dir (default: <repo>/docs/screenshots/<feature>/)
  --no-backend        skip the backend health check even if the screen needs one
  --device <name>     simulator name substring or UDID (default: single booted device, else 4509FAFA…)
  --reuse-installed   skip rebuild/install; fail if app missing from the simulator

Exit codes: 0 ok · 1 args/unknown screen · 2 simulator unavailable · 3 backend unreachable · 4 launch/crash · 5 nav/settle timeout · 6 write failure
EOF
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --out) OUT_DIR="${2:-}"; shift 2 ;;
    --no-backend) NO_BACKEND=1; shift ;;
    --device) DEVICE="${2:-}"; shift 2 ;;
    --reuse-installed) REUSE_INSTALLED=1; shift ;;
    -h|--help) usage ;;
    -*) echo "unknown option: $1" >&2; usage ;;
    *)
      if [ -z "$SCREEN" ]; then SCREEN="$1"; shift
      else echo "unexpected argument: $1" >&2; usage; fi
      ;;
  esac
done
[ -z "$SCREEN" ] && usage

fail() { # fail <exit-code> <title> <body>
  local code="$1" title="$2" body="$3"
  echo "ERROR: $body" >&2
  send_error_report "$title" "$body"
  exit "$code"
}

# --- Resolve the screen from the per-feature registry -------------------------
# Registry is a flat list of `- name:` entries; parsed with a tiny line parser
# (no PyYAML dependency). Output: feature<TAB>route<TAB>deep_link<TAB>initial<TAB>needs_auth<TAB>needs_backend
resolve_screen() {
  python3 - "$1" "$REPO/docs/features" <<'PY'
import glob, os, sys
target, base = sys.argv[1], sys.argv[2]
entries, cur = [], None
for f in sorted(glob.glob(os.path.join(base, "*", "screens.yaml"))):
    feature = os.path.basename(os.path.dirname(f))
    for raw in open(f):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("- name:"):
            if cur is not None:
                entries.append(cur)
            cur = {"_feature": feature, "name": line.split(":", 1)[1].strip()}
        elif cur is not None and ":" in line:
            k, v = (p.strip() for p in line.split(":", 1))
            v = v.split(" #")[0].strip()  # strip inline comments (registry constraint: no " #" inside values)
            cur[k] = v
    if cur is not None:
        entries.append(cur)
        cur = None
for e in entries:
    if e.get("name") == target:
        print("\t".join([e["_feature"], e.get("route", ""), e.get("deep_link", ""),
                         e.get("initial", "false"), e.get("needs_auth", "false"),
                         e.get("needs_backend", "false")]))
        sys.exit(0)
known = ", ".join(e.get("name", "?") for e in entries) or "none registered"
print(f"UNKNOWN_SCREEN: {target} (known: {known})", file=sys.stderr)
sys.exit(1)
PY
}

SCREEN_INFO="$(resolve_screen "$SCREEN")" || fail 1 "capture_screens.sh failed" "unknown screen: $SCREEN"
IFS=$'\t' read -r FEATURE ROUTE DEEP_LINK INITIAL NEEDS_AUTH NEEDS_BACKEND <<< "$SCREEN_INFO"

# needs_auth screens need a restored demo session — deferred to v2 (deep-link scope).
if [ "$NEEDS_AUTH" = "true" ]; then
  fail 5 "capture_screens.sh failed" "screen '$SCREEN' needs_auth — token-restore is v2 scope, not supported in v0"
fi

# Backend health check (only when the screen needs one and --no-backend not set).
if [ "$NEEDS_BACKEND" = "true" ] && [ "$NO_BACKEND" -eq 0 ]; then
  if ! curl -sf "$BACKEND_BASE/health" >/dev/null 2>&1; then
    fail 3 "capture_screens.sh failed" "backend unreachable at $BACKEND_BASE/health (use --no-backend to skip)"
  fi
fi

# --- Simulator -----------------------------------------------------------------
resolve_device() {
  if [ -n "$DEVICE" ]; then
    local line
    line="$(xcrun simctl list devices | grep -i "$DEVICE" | grep -v unavailable | head -1 || true)"
    [ -z "$line" ] && { echo "ERROR: device '$DEVICE' not found" >&2; exit 2; }
    echo "$line" | sed -E 's/.*\(([0-9A-Fa-f-]{36})\).*/\1/'
  else
    local booted
    booted="$(xcrun simctl list devices | grep -i "(Booted)" | grep -v unavailable || true)"
    local count
    count="$(printf '%s\n' "$booted" | grep -c . || true)"
    if [ "$count" -eq 1 ]; then
      printf '%s\n' "$booted" | sed -E 's/.*\(([0-9A-Fa-f-]{36})\).*/\1/'
    elif [ "$count" -gt 1 ]; then
      echo "ERROR: multiple booted simulators — pass --device <name|udid>" >&2
      exit 2
    else
      echo "$DEFAULT_DEVICE_UDID"
    fi
  fi
}
DEVICE_UDID="$(resolve_device)" || exit 2

if ! xcrun simctl list devices | grep -q "$DEVICE_UDID"; then
  fail 2 "capture_screens.sh failed" "simulator '$DEVICE_UDID' not found"
fi
xcrun simctl boot "$DEVICE_UDID" >/dev/null 2>&1 || true # ignore AlreadyBooted
xcrun simctl bootstatus "$DEVICE_UDID" -b >/dev/null 2>&1 || fail 2 "capture_screens.sh failed" "simulator '$DEVICE_UDID' failed to boot"

# --- App bundle id (repo-agnostic; pbxproj may differ per app) ------------------
BUNDLE_ID="$(grep -m1 'PRODUCT_BUNDLE_IDENTIFIER = [^;]*;' "$REPO/ios/Runner.xcodeproj/project.pbxproj" \
  | sed -E 's/.*PRODUCT_BUNDLE_IDENTIFIER = ([^;]*);.*/\1/' | tr -d ' "')"
[ -z "$BUNDLE_ID" ] && fail 1 "capture_screens.sh failed" "could not determine bundle id from $REPO/ios/Runner.xcodeproj"

# --- Build / install ------------------------------------------------------------
installed="$(xcrun simctl get_app_container "$DEVICE_UDID" "$BUNDLE_ID" app 2>/dev/null || true)"
if [ "$REUSE_INSTALLED" -eq 1 ]; then
  if [ -z "$installed" ]; then
    if [ -d "$REPO/build/ios/iphonesimulator/Runner.app" ]; then
      xcrun simctl install "$DEVICE_UDID" "$REPO/build/ios/iphonesimulator/Runner.app" \
        || fail 4 "capture_screens.sh failed" "install failed for $BUNDLE_ID"
    else
      fail 4 "capture_screens.sh failed" "--reuse-installed but $BUNDLE_ID not installed and no artifact at build/ios/iphonesimulator/Runner.app"
    fi
  fi
elif [ -z "$installed" ]; then
  echo "App not installed — building (this can take a while)..."
  (cd "$REPO" && flutter build ios --simulator --no-codesign) || fail 4 "capture_screens.sh failed" "flutter build ios failed"
  xcrun simctl install "$DEVICE_UDID" "$REPO/build/ios/iphonesimulator/Runner.app" \
    || fail 4 "capture_screens.sh failed" "install failed for $BUNDLE_ID"
fi

# --- Navigate --------------------------------------------------------------------
if [ "$INITIAL" = "true" ]; then
  xcrun simctl launch "$DEVICE_UDID" "$BUNDLE_ID" >/dev/null 2>&1 \
    || fail 4 "capture_screens.sh failed" "app launch failed for $BUNDLE_ID"
else
  [ -z "$DEEP_LINK" ] && fail 5 "capture_screens.sh failed" "screen '$SCREEN' is not initial and has no deep_link (v2 URL scheme)"
  xcrun simctl openurl "$DEVICE_UDID" "$DEEP_LINK" >/dev/null 2>&1 \
    || fail 5 "capture_screens.sh failed" "openurl failed for $DEEP_LINK"
fi

# --- Settle detection -------------------------------------------------------------
# Poll two consecutive screenshots; byte-identical => rendered (no spinner).
# Timeout falls back to a fixed wait (best-effort; not an error by itself).
TMPDIR_SS="$(mktemp -d "${TMPDIR:-/tmp}/capture_screens.XXXXXX")"
trap 'rm -rf "$TMPDIR_SS"' EXIT

settle() {
  local a="$TMPDIR_SS/a.png" b="$TMPDIR_SS/b.png" i=0
  xcrun simctl io "$DEVICE_UDID" screenshot "$a" >/dev/null 2>&1
  while [ "$i" -lt "$SETTLE_POLL_SECS" ]; do
    i=$((i + 1))
    sleep 1
    xcrun simctl io "$DEVICE_UDID" screenshot "$b" >/dev/null 2>&1
    if [ "$(shasum -a 256 "$a" | cut -d' ' -f1)" = "$(shasum -a 256 "$b" | cut -d' ' -f1)" ]; then
      echo "screen settled after ~${i}s"
      return 0
    fi
    mv -f "$b" "$a"
  done
  echo "settle timeout — falling back to ${FIXED_WAIT_SECS}s fixed wait"
  sleep "$FIXED_WAIT_SECS"
}
settle

# --- Capture + verify ----------------------------------------------------------------
if [ -z "$OUT_DIR" ]; then
  OUT_DIR="$REPO/docs/screenshots/$FEATURE"
fi
mkdir -p "$OUT_DIR"
TS="$(date +%Y%m%d_%H%M%S)"
OUT_FILE="$OUT_DIR/${SCREEN}_${TS}.png"
xcrun simctl io "$DEVICE_UDID" screenshot "$OUT_FILE" >/dev/null 2>&1 \
  || fail 6 "capture_screens.sh failed" "screenshot write failed: $OUT_FILE"

size="$(stat -f%z "$OUT_FILE" 2>/dev/null || echo 0)"
if [ "$size" -lt "$MIN_PNG_BYTES" ] || ! file "$OUT_FILE" | grep -q "PNG image data"; then
  fail 6 "capture_screens.sh failed" "invalid capture ($size bytes): $OUT_FILE"
fi

# --- PR snippet -----------------------------------------------------------------------
DEVICE_NAME="$(xcrun simctl list devices | grep "$DEVICE_UDID" | head -1 | sed -E 's/^\s*([^(]+).*/\1/' | xargs)"
DATE_H="$(date "+%Y-%m-%d %H:%M")"
cat <<EOF

---
## UI Screenshots — $DATE_H (iOS / $DEVICE_NAME)

![$SCREEN](docs/screenshots/$FEATURE/$(basename "$OUT_FILE"))
> Drag the PNG from Finder into this block to embed.
---

saved: $OUT_FILE
EOF
send_report_to screenshots "capture_screens.sh done" "captured $SCREEN ($size bytes)" "$OUT_FILE"
exit 0
